logging:
  level: info
aws:
  bucketName: chux-crawler
  downloadPath: ~/projects/chux/chux-parser
auth:
  issuerUrl: https://dev-29752729.okta.com/oauth2/default
  tokenUrl: ""
data:
  path: "/home/csailer/projects/chux/chux-parser/data"
bizConfig:
  dataStores:
    - dataStore:
        mongo:
          target: mongo
          uri: mongodb://localhost:27017
          timeout: 10
          databaseName: chux-cprs
          collectionName: ""
